### ISSUE TITLE
Splash Screen Needed

### ISSUE THREAD

**Issue by RahulKesharwani353** [OpInCo-Community/HacktoberWeek#15]
Splash Screen Needed for the project [HacktoberWeek](https://github.com/OpInCo-Community/HacktoberWeek)/[Android-Contributions](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions)/[Note-Keeping-App](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions/Note-Keeping-App)/

Make sure to follow [Code Of Conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/main/CODE_OF_CONDUCT.md) and [Community Guidline](https://github.com/OpInCo-Community/HacktoberWeek#contributing-guidelines)

**Comment by Amandeep404** [comment]
Is there a design for splash screen which I need to follow or it depends on me?

**Comment by RahulKesharwani353** [comment]
It Depends on you!

**Comment by Rarj** [comment]
can you assign it to me, plz?

**Comment by RahulKesharwani353** [comment]
sure @Rarj !

**Comment by Rarj** [comment]
Hi @RahulKesharwani353 , SplashScreen was done!
you can check my work through this [PR](https://github.com/OpInCo-Community/HacktoberWeek/pull/55)

Thanks!

**Comment by RahulKesharwani353** [comment]
Hey We have added a comment, please checkoout

**Comment by Rarj** [comment]
hey, can you specify where file you edit to add that comment. cuz I cannot find your comment on my branch. 
thank you

**Comment by RahulKesharwani353** [comment]
hey, We have successfully reviewed your PR! Thanks for the contribution.
