### ISSUE TITLE
text remains in EditText even after adding new notes

### ISSUE THREAD

**Issue by RahulKesharwani353** [OpInCo-Community/HacktoberWeek#16]
There is a bug in [HacktoberWeek](https://github.com/OpInCo-Community/HacktoberWeek)/[Android-Contributions](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions)/[Note-Keeping-App](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions/Note-Keeping-App)/, EditText is not getting cleared even after aading new task.

Make sure to follow [Code Of Conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/main/CODE_OF_CONDUCT.md) and [Community Guidline](https://github.com/OpInCo-Community/HacktoberWeek#contributing-guidelines)

**Comment by Amandeep404** [comment]
Can I be assigned to this task?

**Comment by RahulKesharwani353** [comment]
Hello @Amandeep404! we have already assigned you with an issue, It would be appreciated  if you contribute to that, once done we can move forward with this issue

**Comment by Amandeep404** [comment]
@RahulKesharwani353 pls look to this pr and accept it if no other changes are required
