### ISSUE TITLE
Enhance layout and UI for the Note App

### ISSUE THREAD

**Issue by RahulKesharwani353** [OpInCo-Community/HacktoberWeek#18]
We need to enhance the UI for Notes in [HacktoberWeek](https://github.com/OpInCo-Community/HacktoberWeek)/[Android-Contributions](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions)/[Note-Keeping-App](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions/Note-Keeping-App)/

Make sure to follow [Code Of Conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/main/CODE_OF_CONDUCT.md) and [Community Guidline](https://github.com/OpInCo-Community/HacktoberWeek#contributing-guidelines)

**Comment by gvadam** [comment]
Hi, can you assign this to me?

**Comment by RahulKesharwani353** [comment]
Yesss! You can work on it
