### ISSUE TITLE
Alert Box Should Be there, before deleting

### ISSUE THREAD

**Issue by RahulKesharwani353** [OpInCo-Community/HacktoberWeek#19]
There should be alert box or an confirmation, before deleting any notes in [HacktoberWeek](https://github.com/OpInCo-Community/HacktoberWeek)/[Android-Contributions](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions)/[Note-Keeping-App](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions/Note-Keeping-App)/

Make sure to follow [Code Of Conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/main/CODE_OF_CONDUCT.md) and [Community Guidline](https://github.com/OpInCo-Community/HacktoberWeek#contributing-guidelines)

**Comment by Amandeep404** [comment]
Can I be assigned to this task?

**Comment by RahulKesharwani353** [comment]
yaah sure
