### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by Shanks2121** [OpInCo-Community/HacktoberWeek#22]
Add a Simple Splash Screen in the MemeShare App

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/OpInCo-Community/HacktoberWeek/blob/411f342658c2817f7c0b6c324f7ae6cb336d3c83/CONTRIBUTING.md) and [code of conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/411f342658c2817f7c0b6c324f7ae6cb336d3c83/CODE_OF_CONDUCT.md).

**Comment by neil0504** [comment]
Hey @Shanks2121 , I would like to work on this issue. Plz assign it to me.

**Comment by RahulKesharwani353** [comment]
Hey @neil0504, you can start working on it. Make sure to follow the proper guidelines.

Happy Coding : )
