### ISSUE TITLE
Change shape and color of the buttons

### ISSUE THREAD

**Issue by Shanks2121** [OpInCo-Community/HacktoberWeek#23]
Change the shape of buttons to circle and the color of the button to any color in [HacktoberWeek](https://github.com/OpInCo-Community/HacktoberWeek)/[Android-Contributions](https://github.com/OpInCo-Community/HacktoberWeek/tree/main/Android-Contributions)/MemeShare/ 

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/OpInCo-Community/HacktoberWeek/blob/411f342658c2817f7c0b6c324f7ae6cb336d3c83/CONTRIBUTING.md) and [code of conduct](https://github.com/OpInCo-Community/HacktoberWeek/blob/411f342658c2817f7c0b6c324f7ae6cb336d3c83/CODE_OF_CONDUCT.md).

**Comment by piyushsahu1** [comment]
i want to contribute

**Comment by Amandeep404** [comment]
Can I be assigned to this task?

**Comment by RahulKesharwani353** [comment]
Hey @Amandeep404! Sure, you can

**Comment by RahulKesharwani353** [comment]
Thanks for the contribution
